services:
  - type: web
    name: visionattend-ai
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        value: postgresql://postgres.ratyewbiahwjgwoymzct:Prathvi%404688@aws-0-ap-south-1.pooler.supabase.com:5432/postgres
      - key: SUPABASE_URL
        value: https://ratyewbiahwjgwoymzct.supabase.co
      - key: SUPABASE_BUCKET
        value: attendance-media
      - key: SECRET_KEY
        generateValue: true
