# -*- coding: utf-8 -*-
"""day2_opencv_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QWHV0fMqjyUm533Eke4pBQ3BEMUoeEoq
"""

!pip uninstall -y opencv-python opencv-python-headless
!pip install opencv-contrib-python-headless

import cv2

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

images = ['/content/single person.jpeg', '/content/sideface.jpeg', '/content/group of people.jpeg']

for img_path in images:
    img = cv2.imread(img_path)
    if img is None:
        print(f"Could not read {img_path} — check the file exists")
        continue

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))

    print(f"{img_path}: {len(faces)} face(s) detected")

    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)

    output_name = img_path.split('/')[-1]
    cv2.imwrite(f"output_images/output_{output_name}", img)

