# -*- coding: utf-8 -*-
"""day3 face recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjmb8wavzkx8lz3G9OnYFgoi5s7NO_gJ
"""

!pip install face_recognition

from sklearn.datasets import fetch_lfw_people

# Load dataset with people who have multiple photos
lfw = fetch_lfw_people(min_faces_per_person=2, resize=0.5)

print(f"Total images: {lfw.images.shape[0]}")
print(f"People: {len(lfw.target_names)}")

import numpy as np

# Find a person with at least 2 photos
target_name = lfw.target_names[0]
indices = np.where(lfw.target == 0)[0]

print(f"Person: {target_name}")
print(f"Number of photos available: {len(indices)}")

# Save first two photos as images
from PIL import Image
img1 = Image.fromarray((lfw.images[indices[0]] * 255).astype('uint8'))
img2 = Image.fromarray((lfw.images[indices[1]] * 255).astype('uint8'))
img1.save('known_face.jpg')
img2.save('test_face.jpg')

print("Saved known_face.jpg and test_face.jpg")

import face_recognition

known_image = face_recognition.load_image_file("known_face.jpg")
known_encoding = face_recognition.face_encodings(known_image)

test_image = face_recognition.load_image_file("test_face.jpg")
test_encoding = face_recognition.face_encodings(test_image)

if len(known_encoding) == 0 or len(test_encoding) == 0:
    print("Face not detected in one of the images")
else:
    result = face_recognition.compare_faces([known_encoding[0]], test_encoding[0])
    distance = face_recognition.face_distance([known_encoding[0]], test_encoding[0])
    print(f"Same person match: {result[0]}")
    print(f"Confidence (lower = better match): {distance[0]:.4f}")

+++