# -*- coding: utf-8 -*-
"""day3 face recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjmb8wavzkx8lz3G9OnYFgoi5s7NO_gJ
"""

!pip install face_recognition

from sklearn.datasets import fetch_lfw_people

# Load dataset with people who have multiple photos
lfw = fetch_lfw_people(min_faces_per_person=2, resize=0.5)

print(f"Total images: {lfw.images.shape[0]}")
print(f"People: {len(lfw.target_names)}")

import numpy as np

# Find a person with at least 2 photos
target_name = lfw.target_names[0]
indices = np.where(lfw.target == 0)[0]

print(f"Person: {target_name}")
print(f"Number of photos available: {len(indices)}")

# Save first two photos as images
from PIL import Image
img1 = Image.fromarray((lfw.images[indices[0]] * 255).astype('uint8'))
img2 = Image.fromarray((lfw.images[indices[1]] * 255).astype('uint8'))
img1.save('known_face.jpg')
img2.save('test_face.jpg')

print("Saved known_face.jpg and test_face.jpg")

import face_recognition

known_image = face_recognition.load_image_file("known_face.jpg")
known_encoding = face_recognition.face_encodings(known_image)

test_image = face_recognition.load_image_file("test_face.jpg")
test_encoding = face_recognition.face_encodings(test_image)

if len(known_encoding) == 0 or len(test_encoding) == 0:
    print("Face not detected in one of the images")
else:
    result = face_recognition.compare_faces([known_encoding[0]], test_encoding[0])
    distance = face_recognition.face_distance([known_encoding[0]], test_encoding[0])
    print(f"Same person match: {result[0]}")
    print(f"Confidence (lower = better match): {distance[0]:.4f}")

!pip install  opencv-python mediapipe



!pip install mtcnn pillow -q

import os
from PIL import Image, ImageDraw
import matplotlib.pyplot as plt
from mtcnn import MTCNN

# 1. Initialize Pure-Python Detector (No OpenCV required)
detector = MTCNN()

dataset_path = 'data/raw_student_dataset'

if not os.path.exists(dataset_path):
    print(f"❌ ERROR: '{dataset_path}' path nahi mila.")
else:
    image_count = 0
    for root, dirs, files in os.walk(dataset_path):
        for file in files:
            if file.lower().endswith(('.jpg', '.jpeg', '.png')):
                image_count += 1
                img_path = os.path.join(root, file)
                print(f"[{image_count}] Processing: {img_path}")

                try:
                    # Read image with PIL
                    img = Image.open(img_path).convert('RGB')

                    # Convert PIL Image to numpy array for MTCNN
                    import numpy as np
                    img_np = np.array(img)

                    # Detect Faces
                    faces = detector.detect_faces(img_np)

                    draw = ImageDraw.Draw(img)
                    detected = False

                    for face in faces:
                        x, y, w, h = face['box']
                        if w > 0 and h > 0:
                            # Draw Green Rectangle
                            draw.rectangle([x, y, x + w, y + h], outline="lime", width=5)
                            detected = True

                    if detected:
                        plt.figure(figsize=(4, 4))
                        plt.imshow(img)
                        plt.axis('off')
                        plt.title(f"Detected: {os.path.basename(root)} / {file}")
                        plt.show()
                    else:
                        print(f"⚠️ No face detected in: {file}")

                except Exception as e:
                    print(f"⚠️ Error on {file}: {e}")

